### ISSUE TITLE
User responding to the bot's Direct Message only submits to the Moderators for a short amount of time.

### ISSUE THREAD

**Issue by ItsNitesky** [marshmatter/voids-discord-bot#1]
When a moderator uses /warn or /notify directed at a user, the user may only reply within a few minutes time, otherwise the message never gets pushed through to the moderators and it does not currently alert the user that it is not being submitted back.

Two conditionals should be:

1 - User is able to respond successfully to Moderator messages (/warn or /notify) and should confirm that the message is sent.

2 - User is unable to respond successfully to Moderator messages (/warn or /notify) and should be informed that the message was not sent and that they can open a ticket in the #help-me(?) channel

(help channel tbd)

**Comment by ItsNitesky** [comment]
Making this so I remember after I sleep - will fix this shortly.

**Comment by DigitalPhantoms** [comment]
for right now we are having people use /new with the ticket bot

**Comment by ItsNitesky** [comment]
Fixed in **v1.0.1**
