### ISSUE TITLE
/listwarning

### ISSUE THREAD

**Issue by DigitalPhantoms** [marshmatter/voids-discord-bot#2]
only ID 1 and ID 7 show up on the list

**Comment by ItsNitesky** [comment]
This should be fixed when it's moved to a different database. Updated warning IDs already.

the command will now only show information to the individual that does the /listwarning command to prevent chat spam.

**Comment by ItsNitesky** [comment]
I've reset the increments for every table in the bot's database, so they should all start from 1 now.
