### ISSUE TITLE
Submission Descriptions

### ISSUE THREAD

**Issue by DigitalPhantoms** [marshmatter/voids-discord-bot#5]
Matt likes that people add lore or breakdowns of what they did for the image submission so there should be a text box that says "tell us about your city". It should not be mandatory,

**Comment by ItsNitesky** [comment]
Will add an **optional** rule for the submit command allowing users to provide lore behind their screenshots.

**Comment by ItsNitesky** [comment]
Added the optional rule to add a description to your submission now.
