### ISSUE TITLE
/deletewarning

### ISSUE THREAD

**Issue by DigitalPhantoms** [marshmatter/voids-discord-bot#6]
Create /deletewarning for when someone needs to clear someones warnings if a mistake is made.

**Comment by DigitalPhantoms** [comment]
make it /clearwarning as /deletewarning already exists

**Comment by ItsNitesky** [comment]
Should this clear all warnings attached to a user or should this require a warning ID so it only clears the specified warning?

It's certainly quite difficult to "accidentally" warn a user as you need to get a warning ID from the list of warnings.

**Comment by DigitalPhantoms** [comment]
should clear all warnings since it would more than likely only be clearing the 1 accidental. if it needs to change we will revisit

**Comment by ItsNitesky** [comment]
The command "/clearwarnings" has been created.
